version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_BACKEND_URL: http://localhost:8000
    ports:
      - "5173:80"
    depends_on:
      - backend
